### ISSUE TITLE
bug: Allow uppercase characters in URL

### ISSUE THREAD

**Issue by dennismphil** [slackapi/deno-slack-runtime#46]
### Describe the bug

Slack allows only lowercase characters in outgoing domain URLs

### Requirements
* [X] I've read and understood the [Contributing guidelines](../CONTRIBUTING.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

### To Reproduce

* Create a manifest with `outgoingDomains: ["ABCD.example.com"]`
* Note the manifest verification fails with a failed constraint error message 

### Expected behavior

* Allow uppercase characters in URLs 
* Match [RFC1738](https://www.ietf.org/rfc/rfc1738.txt)

Though most URLs are case-insensitive, would be neat to see Slack supporting uppercase characters

#### Screenshots

![2023-02-21_00-39-27](https://user-images.githubusercontent.com/4141366/220418986-baa0c918-2837-435a-a6d2-0a5ab0e445b6.png)

**Comment by shapirone** [comment]
Thanks for the report, we'll look into this!

**Comment by curtisallen** [comment]
Thanks for the report @dennismphil a fix has been rolled out 🙇🏾
